function createfigurestim(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Jun-2017 17:40:22

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'Parent',axes1);
set(loglog1(1),'DisplayName','Euler (expl)','Marker','diamond');
set(loglog1(2),'DisplayName','Heun','Marker','pentagram');
set(loglog1(3),'DisplayName','RK3 (expl)','Marker','hexagram');
set(loglog1(4),'DisplayName','N^{-1}','LineStyle','-.','Color',[0 0 0]);
set(loglog1(5),'DisplayName','N^{-2}','LineWidth',1.5,'LineStyle',':',...
    'Color',[0 0 0]);
set(loglog1(6),'DisplayName','N^{-3}','LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('Number of integration steps, N');

% Create title
title({'Representative error behaviour','of a single component of the system','with stimulation'});

% Create ylabel
ylabel('Relative error');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','XTick',...
    [1 2 4 8 16 32 50],'YGrid','on','YMinorTick','on','YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.145241473456583 0.13032977306321 0.202280409043004 0.264175265343593]);

